### ISSUE TITLE
7.0.1 & websockets - unable to find socket.io.min.js

### ISSUE THREAD

**Issue by mattstone** [thoov/ember-websockets#139]
Process to replicate issue

1. create new ember app - ember new test app
2. cd testapp
3. ember s successfully runs the server
4. install ember-websockets - ember install ember-websockets & npm install
5. ember s successfully runs the server
6. update config/environment.js to load web sockets
7. ember s now throws error.

Looking in the tmp/source_map_concat-input_base_path-Ij5PCZFx.tmp directory, there are no files there.

I'm a bit of a loss as to where to start troubleshooting.

Error:

Zen:testapp matt$ ember s
Livereload server on http://localhost:49154
Serving on http://localhost:4200/
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, open '/Users/matt/projects/testapp/tmp/source_map_concat-input_base_path-Ij5PCZFx.tmp/vendor/ember-websockets/socket.io-client/socket.io.min.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at SourceMap.addFile (/Users/matt/projects/testapp/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /Users/matt/projects/testapp/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (native)
    at Concat.<anonymous> (/Users/matt/projects/testapp/node_modules/broccoli-concat/concat.js:198:24)
    at /Users/matt/projects testapp/node_modules/fast-sourcemap-concat/lib/source-map.js:393:12
    at initializePromise (/Users/matt/projects/testapp/node_modules/rsvp/dist/rsvp.js:589:5)
    at new Promise$1 (/Users/matt/projects/testapp/node_modules/rsvp/dist/rsvp.js:1077:33)
    at SourceMap.end (/Users/matt/projects/testapp/node_modules/fast-sourcemap-concat/lib/source-map.js:380:10)

The broccoli plugin was instantiated at: 
    at Concat.Plugin (/Users/matt/projects/testapp/node_modules/broccoli-plugin/index.js:7:31)
    at new Concat (/Users/matt/projects/testapp/node_modules/broccoli-concat/concat.js:38:10)
    at module.exports (/Users/matt/projects/testapp/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/Users/matt/projects/testapp/node_modules/ember-cli/lib/broccoli/ember-app.js:397:10)
    at EmberApp._concatFiles (/Users/matt/projects/testapp/node_modules/ember-cli/lib/broccoli/ember-app.js:410:15)
    at EmberApp.javascript (/Users/matt/projects/testapp/node_modules/ember-cli/lib/broccoli/ember-app.js:1286:12)
    at EmberApp.toArray (/Users/matt/projects/testapp/node_modules/ember-cli/lib/broccoli/ember-app.js:1668:10)
    at EmberApp.toTree (/Users/matt/projects/testapp/node_modules/ember-cli/lib/broccoli/ember-app.js:1690:30)
    at module.exports (/Users/matt/projects/testapp/ember-cli-build.js:22:14)
    at Builder.setupBroccoliBuilder (/Users/matt/projects/testapp/node_modules/ember-cli/lib/models/builder.js:54:19)

package.json

{
  "name": "testapp",
  "version": "0.0.0",
  "description": "Small description for testapp goes here",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^2.4.1",
    "ember-cli": "2.12.1",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-eslint": "^3.0.0",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.6",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^3.1.0",
    "ember-cli-shims": "^1.0.2",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.12.0",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.6.0",
    "ember-resolver": "^2.0.3",
    "ember-source": "~2.12.0",
    "ember-websockets": "^7.0.1",
    "ember-welcome-page": "^2.0.2",
    "loader.js": "^4.2.3"
  },
  "engines": {
    "node": ">= 4"
  },
  "private": true
}

bower.json

{
  "name": "test app",
  "dependencies": {
  }
}

**Comment by Ebsy** [comment]
+1 on this. I had this problem yesterday after upgrading. I'm pretty sure it's just in the new index.js where you're requiring the socket.io dist files (older version references the 'dist' folder explicitly, new version doesn't that's the problem) I simply downgraded back to 7.0.0 and all is good

https://github.com/thoov/ember-websockets/commit/602acd170d4e541c12dbef3e3075b9464d2c0402#diff-168726dbe96b3ce427e7fedce31bb0bc

**Comment by thoov** [comment]
@mattstone @Ebsy Thanks for reporting this issue. I can reproduce it and I am working on a solution. Should be fixed today and I will leave a comment here once I push the fix to npm.

**Comment by thoov** [comment]
I just published v7.0.2 which should fix this. Let me know if you guys are running into this still.

**Comment by mattstone** [comment]
All good here. Thanks for the speedy response.
