### ISSUE TITLE
not working as a dependency of an addon

### ISSUE THREAD

**Issue by BryanCrotaz** [thoov/ember-websockets#146]
create an addon
add `ember-websockets` as a dependency
Use the addon in an app.

Build time error:
```TypeError: Cannot read property 'project' of undefined
    at Class._readConfig (C:\projects\lords-scoreboard-ui\node_modules\ember-websockets\index.js:39:29)
    at Class._readConfigProp (C:\projects\lords-scoreboard-ui\node_modules\ember-websockets\index.js:61:25)
    at Class.included (C:\projects\lords-scoreboard-ui\node_modules\ember-websockets\index.js:19:14)
    at Class.superWrapper [as included] (C:\projects\lords-scoreboard-ui\node_modules\core-object\lib\assign-properties.js:34:20)
```
this.app is undefined in the build step?

**Comment by JonathanBristow** [comment]
Has this been looked in to? I'm having the same problem and was just about to fork and debug it.
