### ISSUE TITLE
Path or pattern "bower_components/uri.js/src/URI.min.js" did not match any files

### ISSUE THREAD

**Issue by jackmatt2** [thoov/ember-websockets#38]
When install this and run my server `ember s` I get the following error:

```
Path or pattern "bower_components/uri.js/src/URI.min.js" did not match any files
```

**Comment by thoov** [comment]
@jackmatt2 Thanks for opening this issue. I just ran these commands to test it the baseline:

```shell
ember new testapp
cd testapp
ember install ember-websockets
ember s
```

And I want not able to get the error you mentioned. Can you give me some info on your setup (what version of ember-cli, are you running on windows)? Also can you let me know how you installed the addon?

**Comment by jackmatt2** [comment]
OS: Fedora Linux 20

```bash
$ ember --version
version: 0.2.7
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
node: 0.12.2
npm: 2.11.0
```

Installed using `ember install ember-websockets` but get the error below while installing.
```
version: 0.2.7
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Installed packages for tooling via npm.
Cannot read property 'name' of undefined                                                                                                                                                       
TypeError: Cannot read property 'name' of undefined                                                                                                                                            
    at /home/jack/git/my-project/node_modules/ember-cli/lib/models/project.js:482:53                                                                                      
    at baseFindIndex (/home/jack/git/my-project/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)                                                
    at /home/jack/git/my-project/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19                                                                  
    at Project.findAddonByName (/home/jack/git/my-project/node_modules/ember-cli/lib/models/project.js:481:20)                                                            
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/home/jack/git/my-project/node_modules/ember-cli/lib/tasks/addon-install.js:63:30)                      
    at Class.module.exports.Task.extend.installBlueprint (/home/jack/git/my-project/node_modules/ember-cli/lib/tasks/addon-install.js:52:30)                              
    at Class.<anonymous> (/home/jack/git/my-project/node_modules/ember-cli/lib/tasks/addon-install.js:42:19)                                                              
    at lib$rsvp$$internal$$tryCatch (/home/jack/git/my-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)                                              
    at lib$rsvp$$internal$$invokeCallback (/home/jack/git/my-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)                                        
    at lib$rsvp$$internal$$publish (/home/jack/git/my-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)


Running `ember s`
```
Path or pattern "bower_components/uri.js/src/URI.min.js" did not match any files
Error: Path or pattern "bower_components/uri.js/src/URI.min.js" did not match any files
    at Object.multiGlob (/home/jack/git/my-project/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/home/jack/git/my-project/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/home/jack/git/my-project/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /home/jack/git/my-project/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/home/jack/git/my-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jack/git/my-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/jack/git/my-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/home/jack/git/my-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

installed using `npm install --save-dev ember-websockets` results in no error during installation but I get the same error when running `ember s`

**Comment by thoov** [comment]
What happens if you run:

```shell
ember install ember-websockets
bower install --save-dev uri.js
ember s
```

**Comment by jackmatt2** [comment]
@thoov Yes, that has fixed the issue.
